(() => {
  const root=document.getElementById("admin");
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
  const save=()=>{SG.save();applyTheme()};
  function applyTheme(){document.documentElement.style.setProperty("--primary",SG.settings.primary);document.documentElement.style.setProperty("--secondary",SG.settings.secondary);document.documentElement.style.setProperty("--bg",SG.settings.bg);document.documentElement.style.setProperty("--text",SG.settings.text);document.documentElement.style.setProperty("--radius",SG.settings.radius+"px");document.documentElement.style.setProperty("--shadow",SG.settings.shadow);document.documentElement.style.setProperty("--font",SG.settings.font)}
  applyTheme();
  const nav=[["dashboard","📊","Dashboard"],["design","🎨","Design Studio"],["builder","🧱","Page Builder"],["notes","📚","Notes / Markdown"],["quizzes","📝","Quiz Builder"],["users","👥","Users"],["analytics","📈","Analytics"],["code","💻","Code Editor"],["settings","⚙️","Settings"]];
  function shell(active,title,body){
    root.innerHTML=`<div class="admin-layout"><aside class="sidebar"><div class="admin-brand"><span class="logo">S</span>StudyGaurav</div>${nav.map(n=>`<button class="side-link ${active===n[0]?"active":""}" data-page="${n[0]}">${n[1]} ${n[2]}</button>`).join("")}<div style="margin-top:20px;border-top:1px solid #334155;padding-top:15px"><a class="side-link" href="index.html">🌐 View Website</a></div></aside><section class="admin-main"><header class="admin-top"><div><b>${title}</b><div class="muted" style="font-size:12px">Control Center</div></div><button class="btn small" id="saveBtn">💾 Save</button></header><div class="admin-content">${body}</div></section></div>`;
    root.querySelectorAll(".side-link[data-page]").forEach(b=>b.onclick=()=>location.hash=b.dataset.page);
    const sb=root.querySelector("#saveBtn"); if(sb)sb.onclick=()=>{save();toast("Saved")};
  }
  function toast(t){const d=document.createElement("div");d.textContent=t;Object.assign(d.style,{position:"fixed",right:"20px",bottom:"20px",padding:"12px 16px",background:"#0f172a",color:"#fff",borderRadius:"10px",zIndex:99});document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
  function dashboard(){
    shell("dashboard","Dashboard",`<div class="admin-grid"><div class="kpi"><span class="muted">Users</span><b>${SG.users.length}</b></div><div class="kpi"><span class="muted">Notes</span><b>${SG.chapters.length}</b></div><div class="kpi"><span class="muted">Quizzes</span><b>${SG.quizzes.length}</b></div><div class="kpi"><span class="muted">Avg. score</span><b>78%</b></div></div><div class="panel"><h3>🚀 Quick actions</h3><div class="toolbar"><button class="btn primary" onclick="location.hash='notes'">+ Add Markdown Note</button><button class="btn" onclick="location.hash='quizzes'">+ Create Quiz</button><button class="btn" onclick="location.hash='builder'">Open Page Builder</button><button class="btn" onclick="location.hash='design'">Edit Design</button></div></div><div class="panel"><h3>System</h3><div class="notice">यह complete frontend CMS demo है। Real multi-device admin login/database के लिए Supabase connection नीचे Settings में जोड़ा जाएगा।</div><p class="muted">आप यहाँ से design, pages, Markdown notes, quizzes, users और analytics manage कर सकते हैं।</p></div>`);
  }
  function design(){
    shell("design","Design Studio",`<div class="panel"><h3>Global appearance</h3><div class="form-grid"><div class="field"><label>Primary color</label><input type="color" id="primary" value="${SG.settings.primary}"></div><div class="field"><label>Secondary color</label><input type="color" id="secondary" value="${SG.settings.secondary}"></div><div class="field"><label>Background</label><input type="color" id="bg" value="${SG.settings.bg}"></div><div class="field"><label>Text color</label><input type="color" id="text" value="${SG.settings.text}"></div><div class="field"><label>Font family</label><select id="font"><option>Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif</option><option>Georgia,serif</option><option>Arial,sans-serif</option><option>system-ui,sans-serif</option></select></div><div class="field"><label>Border radius</label><input id="radius" type="range" min="4" max="32" value="${SG.settings.radius}"></div></div><div class="toolbar"><button class="btn primary" id="apply">Apply & Save</button><button class="btn" onclick="location.hash='builder'">Open Visual Builder →</button></div></div><div class="panel"><h3>Responsive preview</h3><div class="toolbar"><button class="btn small" onclick="toast('Desktop preview')">🖥 Desktop</button><button class="btn small" onclick="toast('Tablet preview')">📱 Tablet</button><button class="btn small" onclick="toast('Mobile preview')">📲 Mobile</button></div><div class="card"><h2>Live design sample</h2><p class="muted">Colors, typography, cards and buttons follow your saved theme.</p><button class="btn primary">Primary Button</button></div></div>`);
    const f=root.querySelector("#font");f.value=SG.settings.font;root.querySelector("#apply").onclick=()=>{["primary","secondary","bg","text"].forEach(k=>SG.settings[k]=root.querySelector("#"+k).value);SG.settings.font=f.value;SG.settings.radius=+root.querySelector("#radius").value;save();toast("Theme saved");};
  }
  function builder(){
    let blocks=JSON.parse(localStorage.getItem("sg_builder")||"null")||[
      {type:"hero",title:"Learn faster. Practice better.",text:"Your smarter study space.",button:"Explore Subjects →"},
      {type:"cards",title:"Choose your subject",text:"History, Polity and Quizzes"},
      {type:"text",title:"About StudyGaurav",text:"Add your own section from the admin panel."}
    ];
    let selected=0;
    const palette=`<div class="palette"><b>Drag / add blocks</b><div class="palette-item" data-add="hero">🦸 Hero</div><div class="palette-item" data-add="text">📝 Text</div><div class="palette-item" data-add="cards">🗂 Cards</div><div class="palette-item" data-add="button">🔘 Button</div><div class="palette-item" data-add="html">💻 Custom HTML</div></div>`;
    const render=()=>{const canvas=blocks.map((b,i)=>`<div class="builder-block ${i===selected?"selected":""}" draggable="true" data-i="${i}">${i===selected?`<div class="block-actions"><button class="tiny" data-del="${i}">🗑</button></div>`:""}${b.type==="hero"?`<span class="badge">Hero</span><h1>${esc(b.title)}</h1><p>${esc(b.text)}</p><button class="btn primary">${esc(b.button)}</button>`:b.type==="cards"?`<h2>${esc(b.title)}</h2><p>${esc(b.text)}</p><div class="cards"><div class="card">📜 History</div><div class="card">⚖️ Polity</div><div class="card">📝 Quizzes</div></div>`:b.type==="button"?`<button class="btn primary">${esc(b.title)}</button>`:b.type==="html"?`<pre><code>${esc(b.text)}</code></pre>`:`<h2>${esc(b.title)}</h2><p>${esc(b.text)}</p>`}</div>`).join("");root.querySelector("#canvas").innerHTML=canvas;bindCanvas();updateInspector()};
    shell("builder","Visual Page Builder",`<div class="panel"><div class="toolbar"><button class="btn primary" id="saveBuilder">💾 Save layout</button><button class="btn" id="previewBuilder">👁 Preview</button><span class="muted">Click a block, edit on right, drag to reorder.</span></div><div class="builder">${palette}<div class="canvas" id="canvas"></div><div class="inspector" id="inspector"></div></div></div>`);
    const updateInspector=()=>{const b=blocks[selected]||{};root.querySelector("#inspector").innerHTML=`<h3>Inspector</h3><div class="field"><label>Block type</label><input disabled value="${b.type||""}"></div><div class="field" style="margin-top:10px"><label>Title / heading</label><input id="ititle" value="${esc(b.title||"")}"></div><div class="field" style="margin-top:10px"><label>Text / content</label><textarea id="itext">${esc(b.text||"")}</textarea></div><div class="field" style="margin-top:10px"><label>Button label</label><input id="ibutton" value="${esc(b.button||"")}"></div>`};
    const bindCanvas=()=>{root.querySelectorAll(".builder-block").forEach(el=>{el.onclick=()=>{selected=+el.dataset.i;render()};el.ondragstart=e=>e.dataTransfer.setData("text/plain",el.dataset.i);el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const from=+e.dataTransfer.getData("text/plain"),to=+el.dataset.i;const [x]=blocks.splice(from,1);blocks.splice(to,0,x);selected=to;render()}});root.querySelectorAll("[data-del]").forEach(b=>b.onclick=e=>{e.stopPropagation();blocks.splice(+b.dataset.del,1);selected=Math.max(0,selected-1);render()})};
    root.querySelectorAll("[data-add]").forEach(x=>x.onclick=()=>{const t=x.dataset.add;blocks.push(t==="hero"?{type:t,title:"New Hero",text:"Edit this section.",button:"Get Started"}:t==="cards"?{type:t,title:"New Cards",text:"Edit cards content."}:t==="button"?{type:t,title:"New Button"}:t==="html"?{type:t,title:"Custom HTML",text:"<section>Custom block</section>"}:{type:"text",title:"New Section",text:"Write your content here."});selected=blocks.length-1;render()});
    root.querySelector("#saveBuilder").onclick=()=>{localStorage.setItem("sg_builder",JSON.stringify(blocks));toast("Layout saved")};
    root.querySelector("#previewBuilder").onclick=()=>toast("Preview saved layout on your public site after publishing integration");
    root.querySelector("#inspector").addEventListener("input",e=>{const b=blocks[selected];if(!b)return;if(e.target.id==="ititle")b.title=e.target.value;if(e.target.id==="itext")b.text=e.target.value;if(e.target.id==="ibutton")b.button=e.target.value;});
    render();
  }
  function notes(){
    shell("notes","Notes / Markdown",`<div class="panel"><h3>Add / edit Markdown note</h3><div class="form-grid"><div class="field"><label>Subject</label><select id="nsub">${SG.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></div><div class="field"><label>Chapter title</label><input id="ntitle" placeholder="e.g. गुप्त साम्राज्य"></div><div class="field full"><label>Markdown content</label><textarea id="nmd" placeholder="# Heading\n\nWrite or paste your .md content here..."></textarea></div></div><div class="toolbar"><label class="btn">📎 Choose .md <input id="mdfile" type="file" accept=".md,.markdown,text/markdown" hidden></label><button class="btn primary" id="publishNote">Publish Note</button></div><div class="split"><div><h3>Editor</h3><textarea id="editor" style="width:100%;min-height:380px;border:1px solid var(--border);border-radius:12px;padding:15px" placeholder="# Your Markdown"></textarea></div><div><h3>Live Preview</h3><div class="preview markdown" id="mdpreview"></div></div></div></div><div class="panel"><h3>Published notes</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Subject</th><th>Chapter</th><th>Actions</th></tr></thead><tbody>${SG.chapters.map((c,i)=>`<tr><td>${esc(SG.subjects.find(s=>s.id===c.subject)?.name||c.subject)}</td><td>${esc(c.title)}</td><td><button class="btn small" data-editnote="${i}">Edit</button> <button class="btn small danger" data-delnote="${i}">Delete</button></td></tr>`).join("")}</tbody></table></div></div>`);
    const editor=root.querySelector("#editor"),preview=root.querySelector("#mdpreview"),title=root.querySelector("#ntitle"),sub=root.querySelector("#nsub");
    const update=()=>preview.innerHTML=md(editor.value||"*Live Markdown preview*"); editor.oninput=update;
    root.querySelector("#mdfile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{editor.value=r.result;update();if(!title.value)title.value=f.name.replace(/\\.md$/i,"").replace(/[-_]/g," ")};r.readAsText(f)};
    root.querySelector("#publishNote").onclick=()=>{if(!title.value.trim()||!editor.value.trim())return toast("Title and Markdown required");SG.chapters.push({id:"n-"+Date.now(),subject:sub.value,title:title.value.trim(),md:editor.value});save();toast("Note published");setTimeout(()=>location.reload(),500)};
    root.querySelectorAll("[data-delnote]").forEach(b=>b.onclick=()=>{SG.chapters.splice(+b.dataset.delnote,1);save();location.reload()});
    root.querySelectorAll("[data-editnote]").forEach(b=>b.onclick=()=>{const c=SG.chapters[+b.dataset.editnote];title.value=c.title;sub.value=c.subject;editor.value=c.md;update();window.scrollTo({top:0,behavior:"smooth"})});
  }
  function quizzes(){
    shell("quizzes","Quiz Builder",`<div class="panel"><h3>Create quiz</h3><div class="form-grid"><div class="field"><label>Subject</label><select id="qsub">${SG.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></div><div class="field"><label>Quiz title</label><input id="qtitle" placeholder="e.g. History Chapter 1 Quiz"></div><div class="field full"><label>Questions JSON</label><textarea id="qjson">[
  {"q":"Question?","options":["A","B","C","D"],"answer":0,"explanation":"Why this is correct."}
]</textarea></div></div><button class="btn primary" id="publishQuiz">Publish Quiz</button></div><div class="panel"><h3>Published quizzes</h3>${SG.quizzes.map((q,i)=>`<div class="chapter"><div><b>${esc(q.title)}</b><small>${q.questions.length} questions</small></div><button class="btn small danger" data-delq="${i}">Delete</button></div>`).join("")}</div>`);
    root.querySelector("#publishQuiz").onclick=()=>{try{const questions=JSON.parse(root.querySelector("#qjson").value);if(!root.querySelector("#qtitle").value.trim())throw 0;SG.quizzes.push({id:"q-"+Date.now(),subject:root.querySelector("#qsub").value,title:root.querySelector("#qtitle").value,questions});save();toast("Quiz published");setTimeout(()=>location.reload(),500)}catch(e){toast("Check title and JSON")}};
    root.querySelectorAll("[data-delq]").forEach(b=>b.onclick=()=>{SG.quizzes.splice(+b.dataset.delq,1);save();location.reload()});
  }
  function users(){
    shell("users","User Management",`<div class="panel"><div class="toolbar"><input id="userSearch" class="field" style="padding:10px;width:280px" placeholder="Search user..."></div><div class="table-wrap"><table class="data-table" id="utable"><thead><tr><th>Name</th><th>Email</th><th>Score</th><th>Attempts</th><th>Status</th><th>Action</th></tr></thead><tbody>${SG.users.map((u,i)=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.score}%</td><td>${u.attempts}</td><td>${esc(u.status)}</td><td><button class="btn small danger" data-delu="${i}">Delete</button></td></tr>`).join("")}</tbody></table></div></div>`);
    root.querySelectorAll("[data-delu]").forEach(b=>b.onclick=()=>{SG.users.splice(+b.dataset.delu,1);save();location.reload()});
    root.querySelector("#userSearch").oninput=e=>root.querySelectorAll("#utable tbody tr").forEach(r=>r.style.display=r.textContent.toLowerCase().includes(e.target.value.toLowerCase())?"":"none");
  }
  function analytics(){shell("analytics","Analytics",`<div class="admin-grid"><div class="kpi"><span class="muted">Total users</span><b>${SG.users.length}</b></div><div class="kpi"><span class="muted">Quiz attempts</span><b>${SG.users.reduce((a,u)=>a+u.attempts,0)}</b></div><div class="kpi"><span class="muted">Avg score</span><b>${Math.round(SG.users.reduce((a,u)=>a+u.score,0)/Math.max(1,SG.users.length))}%</b></div><div class="kpi"><span class="muted">Published notes</span><b>${SG.chapters.length}</b></div></div><div class="panel"><h3>Performance overview</h3><div class="card"><p>Score distribution</p><div class="progress-track"><i style="width:78%;background:var(--primary)"></i></div><p class="muted">78% average demo performance</p></div></div>`)}
  function code(){
    shell("code","Code Editor",`<div class="notice">⚠️ Custom code is stored locally in this demo. Before enabling server-side publishing, validate/sandbox custom JavaScript so a bad script cannot compromise the whole site.</div><div class="panel"><h3>Custom CSS</h3><textarea id="customcss" style="width:100%;min-height:280px;font-family:monospace">${esc(localStorage.getItem("sg_custom_css")||"/* Your custom CSS */")}</textarea><div class="toolbar"><button class="btn primary" id="savecss">Save CSS</button></div></div><div class="panel"><h3>Custom HTML block</h3><textarea id="customhtml" style="width:100%;min-height:220px;font-family:monospace">${esc(localStorage.getItem("sg_custom_html")||"<!-- Your custom HTML -->")}</textarea><div class="toolbar"><button class="btn primary" id="savehtml">Save HTML</button></div></div>`);
    root.querySelector("#savecss").onclick=()=>{localStorage.setItem("sg_custom_css",root.querySelector("#customcss").value);toast("CSS saved")};root.querySelector("#savehtml").onclick=()=>{localStorage.setItem("sg_custom_html",root.querySelector("#customhtml").value);toast("HTML saved")};
  }
  function settings(){shell("settings","Settings",`<div class="panel"><h3>Admin / backend connection</h3><div class="notice"><b>Next production step:</b> connect Supabase Auth + Database + Storage. Never put a Supabase service-role key in browser code.</div><div class="form-grid"><div class="field"><label>Supabase project URL</label><input placeholder="https://xxxxx.supabase.co"></div><div class="field"><label>Supabase anon/public key</label><input placeholder="eyJ..."></div></div><div class="toolbar"><button class="btn primary" onclick="toast('Connection fields saved in the final backend integration')">Save connection</button></div></div><div class="panel"><h3>Backup</h3><button class="btn" id="export">⬇ Export CMS JSON</button><button class="btn" id="reset" style="margin-left:8px">Reset demo data</button></div>`);
    root.querySelector("#export").onclick=()=>{const blob=new Blob([JSON.stringify({settings:SG.settings,subjects:SG.subjects,chapters:SG.chapters,quizzes:SG.quizzes,users:SG.users},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="studygaurav-backup.json";a.click()};
    root.querySelector("#reset").onclick=()=>{if(confirm("Reset demo data?")){["sg_settings","sg_subjects","sg_chapters","sg_quizzes","sg_users","sg_builder"].forEach(k=>localStorage.removeItem(k));location.reload()}};
  }
  function route(){const h=location.hash.replace("#","")||"dashboard";({dashboard,design,builder,notes,quizzes,users,analytics,code,settings}[h]||dashboard)()}
  window.addEventListener("hashchange",route); route();
})();